"""Generate the noise plate the analog filter falls back to where a shader cannot reach.

Almost every corrupted surface in this mod is filtered by `analog_signal.fsh` now, over the whole
finished frame. One is not, and cannot be: the terminal's weather instrument is a card inside a
larger page, and it must not spill onto the tabs and the close hint the player needs in order to
leave it. A full-frame post chain has no way to express "only this rectangle" - its uniforms are
fixed when it loads, and the card's position on screen is not.

So that surface still draws its grain, and grain is the one thing `GuiGraphics` genuinely cannot do:
it has no per-pixel primitive. Three hundred one-pixel rectangles - which is what this used to be -
is a handful of dots. A tiled 256x256 plate is sixty-five thousand of them for two draws.

Grain lives in the alpha channel with the colour left white, so the same plate can be tinted white
for the light half of the noise and black for the dark half. Plain source-over blending has no
additive mode, and two tinted passes is how zero-mean noise is built without one.
"""

from __future__ import annotations

import json
from pathlib import Path
from random import Random

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
TEXTURE_DIR = ROOT / "src/main/resources/assets/thefourthfrequency/textures/gui/filter"
ART_DIR = ROOT / "docs/art/analog_filter"

GRAIN_SIZE = 256

# Fixed, so a rebuild produces the same bytes and the manifest keeps meaning something.
SEED = 0x4654460A

# Peak alpha of a grain speck. The caller scales this down again; what matters here is that the
# distribution has a long enough tail to look like grain rather than like even static.
GRAIN_PEAK = 205
# Share of the plate that carries any grain at all. Fully dense noise averages out into a flat haze.
GRAIN_DENSITY = 0.34


def grain_plate() -> Image.Image:
    """White RGB, noise in alpha. Tiles seamlessly because every texel is independent."""
    random = Random(SEED)
    image = Image.new("RGBA", (GRAIN_SIZE, GRAIN_SIZE), (255, 255, 255, 0))
    pixels = image.load()
    for y in range(GRAIN_SIZE):
        for x in range(GRAIN_SIZE):
            if random.random() > GRAIN_DENSITY:
                continue
            # Cubed, so most specks are faint and a few are not. A uniform draw gives every speck
            # roughly the same weight, and evenly weighted noise is a texture rather than grain.
            weight = random.random() ** 3
            pixels[x, y] = (255, 255, 255, max(1, int(round(GRAIN_PEAK * weight))))
    return image


def main() -> None:
    TEXTURE_DIR.mkdir(parents=True, exist_ok=True)
    ART_DIR.mkdir(parents=True, exist_ok=True)
    plates = {"tape_grain": grain_plate()}
    manifest = {
        "note": "GENERATED by tools/generate_analog_filter_textures.py - do not hand-edit",
        "seed": SEED,
        "plates": {},
    }
    for name, image in plates.items():
        path = TEXTURE_DIR / f"{name}.png"
        image.save(path, optimize=True)
        manifest["plates"][name] = {
            "width": image.width,
            "height": image.height,
            "bytes": path.stat().st_size,
        }
        print(f"{path.relative_to(ROOT)}  {image.width}x{image.height}  {path.stat().st_size} bytes")
    manifest["plateCount"] = len(manifest["plates"])
    (ART_DIR / "filter_manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
