package com.xm.thefourthfrequency.client_render;

/**
 * Where every part of the world interface samples its material from.
 *
 * <p>GENERATED by {@code tools/world_interface_uv.py --emit-java}. Do not hand-edit: the same
 * script packs these islands and paints the sheets, so an edited offset here points the model at
 * a rectangle nothing was painted into.
 *
 * <p>Parts whose size varies get several islands, and pick one by the same size scalar the
 * generator bucketed on. One island for a whole class would mean the small members sampled only
 * the top-left corner of the large member's island, which is how the old sheet ended up with no
 * part distinguishable from any other.
 */
final class WorldInterfaceUv {
	private WorldInterfaceUv() {
	}

	/** The authored UV canvas; the PNGs are this times the generator's density factor. */
	static final int UV_WIDTH = 256;
	static final int UV_HEIGHT = 128;

	private static int[] pick(int[][] islands, float[] bounds, float key) {
		for (int index = 0; index < bounds.length; index++) {
			if (key <= bounds[index]) return islands[index];
		}
		return islands[bounds.length];
	}

	private static final int[][] BROW = {{197, 41}, {159, 41}};
	private static final float[] BROW_BOUNDS = {0.9F};
	/** brow_0 0.78..0.78; brow_1 1.00..1.00 */
	static int[] brow(float key) {
		return pick(BROW, BROW_BOUNDS, key);
	}
	private static final int[][] CRANIUM = {{82, 24}, {186, 0}};
	private static final float[] CRANIUM_BOUNDS = {0.9F};
	/** cranium_0 0.78..0.78; cranium_1 1.00..1.00 */
	static int[] cranium(float key) {
		return pick(CRANIUM, CRANIUM_BOUNDS, key);
	}
	private static final int[][] EYE = {{132, 41}, {81, 41}};
	private static final float[] EYE_BOUNDS = {0.9F};
	/** eye_0 0.78..0.78; eye_1 1.00..1.00 */
	static int[] eye(float key) {
		return pick(EYE, EYE_BOUNDS, key);
	}
	static final int HORN_U = 51;
	static final int HORN_V = 41;
	private static final int[][] JAW = {{96, 41}, {0, 41}};
	private static final float[] JAW_BOUNDS = {0.9F};
	/** jaw_0 0.78..0.78; jaw_1 1.00..1.00 */
	static int[] jaw(float key) {
		return pick(JAW, JAW_BOUNDS, key);
	}
	static final int KERNEL_FRAME_U = 191;
	static final int KERNEL_FRAME_V = 24;
	static final int KERNEL_GLOW_U = 118;
	static final int KERNEL_GLOW_V = 41;
	private static final int[][] MASS = {{216, 24}, {31, 24}, {91, 0}, {0, 0}};
	private static final float[] MASS_BOUNDS = {4.0F, 6.5F, 9.5F};
	/** mass_0 2.01..3.18; mass_1 4.22..6.46; mass_2 6.50..9.47; mass_3 9.62..13.03 */
	static int[] mass(float key) {
		return pick(MASS, MASS_BOUNDS, key);
	}
	private static final int[][] PLATE = {{231, 41}, {144, 41}, {58, 41}};
	private static final float[] PLATE_BOUNDS = {1.2F, 2.0F};
	/** plate_0 0.59..1.19; plate_1 1.22..1.96; plate_2 2.05..3.11 */
	static int[] plate(float key) {
		return pick(PLATE, PLATE_BOUNDS, key);
	}
	private static final int[][] RIB = {{128, 24}, {0, 24}};
	private static final float[] RIB_BOUNDS = {9.0F};
	/** rib_0 6.79..8.96; rib_1 10.98..12.80 */
	static int[] rib(float key) {
		return pick(RIB, RIB_BOUNDS, key);
	}
	private static final int[][] ROOT = {{43, 41}, {241, 24}};
	private static final float[] ROOT_BOUNDS = {1.0F};
	/** root_0 0.67..0.94; root_1 1.01..1.15 */
	static int[] root(float key) {
		return pick(ROOT, ROOT_BOUNDS, key);
	}
	private static final int[][] TENDRIL = {{112, 24}, {224, 0}, {166, 0}};
	private static final float[] TENDRIL_BOUNDS = {0.8F, 1.2F};
	/** tendril_0 0.64..0.64; tendril_1 1.04..1.04; tendril_2 1.45..1.45 */
	static int[] tendril(float key) {
		return pick(TENDRIL, TENDRIL_BOUNDS, key);
	}
	private static final int[][] TENDRIL_GLOW = {{246, 41}, {189, 41}};
	private static final float[] TENDRIL_GLOW_BOUNDS = {0.7F};
	/** tendril_glow_0 0.64..0.64; tendril_glow_1 0.80..0.80 */
	static int[] tendrilGlow(float key) {
		return pick(TENDRIL_GLOW, TENDRIL_GLOW_BOUNDS, key);
	}
	private static final int[][] TOOTH = {{241, 41}, {183, 41}};
	private static final float[] TOOTH_BOUNDS = {0.9F};
	/** tooth_0 0.78..0.78; tooth_1 1.00..1.00 */
	static int[] tooth(float key) {
		return pick(TOOTH, TOOTH_BOUNDS, key);
	}
	private static final int[][] VERTEBRA = {{28, 41}, {173, 24}, {152, 24}};
	private static final float[] VERTEBRA_BOUNDS = {1.8F, 2.2F};
	/** vertebra_0 1.64..1.64; vertebra_1 1.95..2.10; vertebra_2 2.50..2.50 */
	static int[] vertebra(float key) {
		return pick(VERTEBRA, VERTEBRA_BOUNDS, key);
	}
	static final int WEAPON_BLADE_U = 119;
	static final int WEAPON_BLADE_V = 24;
	static final int WEAPON_FULLER_U = 0;
	static final int WEAPON_FULLER_V = 51;
	static final int WEAPON_GUARD_U = 216;
	static final int WEAPON_GUARD_V = 41;
	static final int WEAPON_HAFT_U = 179;
	static final int WEAPON_HAFT_V = 0;
}
