package com.xm.thefourthfrequency.client_render;

/**
 * Where every part of the world interface samples its material from.
 *
 * <p>GENERATED by {@code tools/world_interface_uv.py --emit-java}. Do not hand-edit: the same
 * script packs these islands and paints the sheets, so an edited offset here points the model at
 * a rectangle nothing was painted into.
 *
 * <p>Parts whose size varies get several islands, and pick one by the same size scalar the
 * generator bucketed on. One island for a whole class would mean the small members sampled only
 * the top-left corner of the large member's island, which is how the old sheet ended up with no
 * part distinguishable from any other.
 */
final class WorldInterfaceUv {
	private WorldInterfaceUv() {
	}

	/** The authored UV canvas; the PNGs are this times the generator's density factor. */
	static final int UV_WIDTH = 256;
	static final int UV_HEIGHT = 128;

	private static int[] pick(int[][] islands, float[] bounds, float key) {
		for (int index = 0; index < bounds.length; index++) {
			if (key <= bounds[index]) return islands[index];
		}
		return islands[bounds.length];
	}

	private static final int[][] BROW = {{191, 86}, {132, 86}, {223, 77}};
	private static final float[] BROW_BOUNDS = {0.75F, 1.0F};
	/** brow_0 0.52..0.74; brow_1 0.88..0.88; brow_2 1.13..1.35 */
	static int[] brow(float key) {
		return pick(BROW, BROW_BOUNDS, key);
	}
	private static final int[][] CORE_COLLAR_POST = {{0, 48}, {103, 27}, {104, 0}};
	private static final float[] CORE_COLLAR_POST_BOUNDS = {6.6F, 9.0F};
	/** core_collar_post_0 5.00..6.00; core_collar_post_1 7.00..8.25; core_collar_post_2 9.20..12.50 */
	static int[] coreCollarPost(float key) {
		return pick(CORE_COLLAR_POST, CORE_COLLAR_POST_BOUNDS, key);
	}
	private static final int[][] CORE_COLLAR_RAIL = {{138, 77}, {176, 77}, {11, 86}};
	private static final float[] CORE_COLLAR_RAIL_BOUNDS = {6.6F, 9.0F};
	/** core_collar_rail_0 5.00..6.00; core_collar_rail_1 7.00..8.25; core_collar_rail_2 9.20..12.50 */
	static int[] coreCollarRail(float key) {
		return pick(CORE_COLLAR_RAIL, CORE_COLLAR_RAIL_BOUNDS, key);
	}
	private static final int[][] CRANIUM = {{0, 64}, {109, 48}, {130, 0}};
	private static final float[] CRANIUM_BOUNDS = {0.75F, 1.0F};
	/** cranium_0 0.52..0.74; cranium_1 0.88..0.88; cranium_2 1.13..1.35 */
	static int[] cranium(float key) {
		return pick(CRANIUM, CRANIUM_BOUNDS, key);
	}
	private static final int[][] DEBRIS = {{0, 77}, {154, 48}, {68, 27}};
	private static final float[] DEBRIS_BOUNDS = {1.9F, 3.0F};
	/** debris_0 0.90..1.89; debris_1 1.90..2.99; debris_2 3.15..4.20 */
	static int[] debris(float key) {
		return pick(DEBRIS, DEBRIS_BOUNDS, key);
	}
	static final int EYE_1_BALL_U = 67;
	static final int EYE_1_BALL_V = 64;
	static final int EYE_1_PUPIL_U = 85;
	static final int EYE_1_PUPIL_V = 86;
	static final int EYE_1_SHUTTER_U = 69;
	static final int EYE_1_SHUTTER_V = 77;
	static final int EYE_2_APERTURE_U = 195;
	static final int EYE_2_APERTURE_V = 64;
	static final int EYE_2_BALL_U = 203;
	static final int EYE_2_BALL_V = 48;
	static final int EYE_2_PUPIL_U = 96;
	static final int EYE_2_PUPIL_V = 77;
	static final int EYE_3_BALL_U = 122;
	static final int EYE_3_BALL_V = 27;
	static final int EYE_3_CAGE_U = 25;
	static final int EYE_3_CAGE_V = 64;
	static final int EYE_3_PUPIL_U = 177;
	static final int EYE_3_PUPIL_V = 64;
	static final int EYE_3_SLIT_U = 40;
	static final int EYE_3_SLIT_V = 77;
	private static final int[][] HORN = {{77, 77}, {151, 64}};
	private static final float[] HORN_BOUNDS = {1.0F};
	/** horn_0 0.74..0.88; horn_1 1.13..1.35 */
	static int[] horn(float key) {
		return pick(HORN, HORN_BOUNDS, key);
	}
	static final int JAW_1_U = 204;
	static final int JAW_1_V = 64;
	static final int JAW_2_U = 34;
	static final int JAW_2_V = 64;
	static final int JAW_3_U = 19;
	static final int JAW_3_V = 48;
	private static final int[][] MASS = {{122, 64}, {163, 27}, {175, 0}, {0, 0}};
	private static final float[] MASS_BOUNDS = {4.0F, 6.5F, 9.5F};
	/** mass_0 2.60..3.40; mass_1 4.09..6.46; mass_2 6.50..9.20; mass_3 9.55..13.83 */
	static int[] mass(float key) {
		return pick(MASS, MASS_BOUNDS, key);
	}
	private static final int[][] MAW = {{109, 77}, {47, 77}, {89, 64}};
	private static final float[] MAW_BOUNDS = {0.75F, 1.0F};
	/** maw_0 0.52..0.74; maw_1 0.88..0.88; maw_2 1.13..1.35 */
	static int[] maw(float key) {
		return pick(MAW, MAW_BOUNDS, key);
	}
	private static final int[][] PLATE = {{181, 86}, {107, 86}, {17, 77}};
	private static final float[] PLATE_BOUNDS = {1.2F, 2.0F};
	/** plate_0 0.58..1.19; plate_1 1.20..1.99; plate_2 2.00..3.19 */
	static int[] plate(float key) {
		return pick(PLATE, PLATE_BOUNDS, key);
	}
	private static final int[][] RIB = {{179, 48}, {216, 27}, {11, 27}};
	private static final float[] RIB_BOUNDS = {9.0F, 13.0F};
	/** rib_0 6.79..8.96; rib_1 9.70..12.82; rib_2 14.01..16.61 */
	static int[] rib(float key) {
		return pick(RIB, RIB_BOUNDS, key);
	}
	static final int RING_FRAGMENT_U = 75;
	static final int RING_FRAGMENT_V = 86;
	static final int RING_INNER_U = 128;
	static final int RING_INNER_V = 77;
	static final int RING_OUTER_U = 160;
	static final int RING_OUTER_V = 64;
	static final int RING_SEGMENT_U = 83;
	static final int RING_SEGMENT_V = 77;
	private static final int[][] ROOT = {{74, 48}, {0, 27}};
	private static final float[] ROOT_BOUNDS = {1.0F};
	/** root_0 0.69..0.99; root_1 1.00..1.37 */
	static int[] root(float key) {
		return pick(ROOT, ROOT_BOUNDS, key);
	}
	private static final int[][] SOCKET = {{207, 86}, {174, 86}, {96, 86}};
	private static final float[] SOCKET_BOUNDS = {0.75F, 1.0F};
	/** socket_0 0.52..0.74; socket_1 0.88..0.88; socket_2 1.13..1.35 */
	static int[] socket(float key) {
		return pick(SOCKET, SOCKET_BOUNDS, key);
	}
	private static final int[][] TENDRIL_1 = {{63, 64}, {11, 48}};
	private static final float[] TENDRIL_1_BOUNDS = {0.5F};
	/** tendril_1_0 0.37..0.37; tendril_1_1 0.61..0.85 */
	static int[] tendril1(float key) {
		return pick(TENDRIL_1, TENDRIL_1_BOUNDS, key);
	}
	private static final int[][] TENDRIL_2 = {{139, 48}, {50, 27}};
	private static final float[] TENDRIL_2_BOUNDS = {0.7F};
	/** tendril_2_0 0.55..0.55; tendril_2_1 0.90..1.25 */
	static int[] tendril2(float key) {
		return pick(TENDRIL_2, TENDRIL_2_BOUNDS, key);
	}
	private static final int[][] TENDRIL_3 = {{114, 27}, {115, 0}};
	private static final float[] TENDRIL_3_BOUNDS = {1.0F};
	/** tendril_3_0 0.77..0.77; tendril_3_1 1.26..1.75 */
	static int[] tendril3(float key) {
		return pick(TENDRIL_3, TENDRIL_3_BOUNDS, key);
	}
	private static final int[][] TENDRIL_GLOW = {{226, 86}, {151, 86}, {122, 86}};
	private static final float[] TENDRIL_GLOW_BOUNDS = {0.5F, 0.8F};
	/** tendril_glow_0 0.38..0.45; tendril_glow_1 0.53..0.78; tendril_glow_2 0.93..1.08 */
	static int[] tendrilGlow(float key) {
		return pick(TENDRIL_GLOW, TENDRIL_GLOW_BOUNDS, key);
	}
	static final int TOOTH_U = 251;
	static final int TOOTH_V = 77;
	private static final int[][] VERTEBRA = {{0, 86}, {234, 64}, {82, 48}};
	private static final float[] VERTEBRA_BOUNDS = {1.2F, 1.9F};
	/** vertebra_0 0.96..1.14; vertebra_1 1.25..1.87; vertebra_2 2.11..3.24 */
	static int[] vertebra(float key) {
		return pick(VERTEBRA, VERTEBRA_BOUNDS, key);
	}
	static final int WEAPON_BLADE_U = 145;
	static final int WEAPON_BLADE_V = 48;
	static final int WEAPON_FULLER_U = 214;
	static final int WEAPON_FULLER_V = 86;
	static final int WEAPON_GUARD_U = 159;
	static final int WEAPON_GUARD_V = 86;
	static final int WEAPON_HAFT_U = 61;
	static final int WEAPON_HAFT_V = 27;
}
